name: Build Module
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: Build Module
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        shell: pwsh
        run: |
          $result = Start-Job { ./build.ps1 -Task Build -Bootstrap } | Receive-Job -Wait
          Write-Output $result
