name: Publish GitHub NuGet Package
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: GithubPackage
    runs-on: windows-latest
    steps:
      - name: Publish GitHub Package
        uses: natescherer/publish-powershell-action@v1.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: packages
