name: Publish GitHub NuGet Package
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: GithubPackage
    runs-on: ubuntu-latest
    steps:
      - uses: natescherer/publish-powershell-action@v1.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: packages
          path: PSXLDevTools
