name: Test Module
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Test
      shell: pwsh
      run: -NoProfile -NonInteractive -File ./build.ps1 -Task Test -Bootstrap
